DraftNews/DraftNews/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
   # Делаем так, чтобы все адреса из нашего приложения (simpleapp/urls.py)
   # подключались к главному приложению с префиксом products/.
   path('newsportal/', include('newsportal.urls')),
    #path('accounts/', include('django.contrib.auth.urls')),
    #path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
]

DraftNews/accounts/urls.py
from django.urls import path
from .views import SignUp

urlpatterns = [
    path('signup', SignUp.as_view(), name='signup'),
    # path('upgrade', upgrade_user, name='account_upgrade'),
]

DraftNews/newsportal/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse

from django.core.cache import cache

from django.utils.translation import gettext as _
from django.utils.translation import pgettext_lazy # импортируем «ленивый» геттекст с подсказкой

class Author(models.Model):

    user_rating = models.IntegerField(default=0) #default = 0.0 ?
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    def update_rating(self):
        """
        *cуммарный рейтинг каждой статьи автора умножается на 3;
        *суммарный рейтинг всех комментариев автора;
        *суммарный рейтинг всех комментариев к статьям автора
        """

        postRat = self.post_set.all().aggregate(postRating=Sum('post_rating'))
        pRat = 0
        pRat += postRat.get("postRating")

        commentAutRat = self.user.comment_set.all().aggregate(commentAutRating=Sum('comm_rating'))
        cRat = 0
        cRat += commentAutRat.get('commentAutRating')


        cuRat = 0

        for i in range(len(self.post_set.all())-1):
            com_us_rat = self.post_set.all()[i].comment_set.all().aggregate(commRates=Sum('comm_rating'))
            cuRat += com_us_rat.get('commRates')


        self.user_rating = pRat *3 + cRat + cuRat
        self.save()



humor = "HUM"
politics = "POL"
science = "SCI"
sport = "SPT"
arts = "ART"

news = 'NEWS'
article = 'ARTL'

CATEGORIES = [
    (humor, 'Юмор'),
    (politics, 'Политика'),
    (science, 'Наука'),
    (sport, 'Спорт'),
    (arts, 'Искусство')
]

TYPES = [
    (news, 'Новость'),
    (article, "Статья")
]



class Category(models.Model):
    category = models.CharField(max_length = 3, choices=CATEGORIES, unique = True)
    subscribers = models.ManyToManyField(User, related_name='categories')

    def __str__(self):
        return self.category

class Post(models.Model):
    author = models.ForeignKey(Author, on_delete = models.CASCADE)
    post_type = models.CharField(max_length=4, choices=TYPES) #news or article
    post_datetime = models.DateTimeField(auto_now_add = True)
    post_title = models.CharField(max_length=64, help_text=_('title of the post'))
    post_body = models.TextField()
    post_rating = models.IntegerField(default=0) #default = 0.0 ?
    categories = models.ManyToManyField(Category, through = "PostCategory")

    def __str__(self):
        return f'{self.post_title.title()}: {self.post_body[:124]}. {self.post_type}'

    def like(self):
        self.post_rating += 1
        self.save()

    def dislike(self):
        self.post_rating -= 1
        self.save()

    def preview(self):
        return self.post_body[:124] + "..."

    def get_absolute_url(self):
        return reverse('exactly_news', args=[str(self.id)])

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)   # сначала вызываем метод родителя, чтобы объект сохранился
        cache.delete(f'post-{self.pk}') # затем удаляем его из кэша, чтобы сбросить его

class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete = models.CASCADE)
    category = models.ForeignKey(Category, on_delete = models.CASCADE)

    def __str__(self):
        return f'{self.post.post_title} | {self.category.category}'

# class Subscription(models.Model):
#     user = models.ForeignKey(
#         to=User,
#         on_delete=models.CASCADE,
#         related_name='subscriptions',
#     )
#     post_type = models.ForeignKey(
#         to=Post,
#         on_delete=models.CASCADE,
#         related_name='subscriptions',
#     )


class Comment(models.Model):
    comm_text = models.TextField()
    comm_datetime = models.DateTimeField(auto_now_add = True)
    comm_rating = models.FloatField(default = 0.0)
    post = models.ForeignKey(Post, on_delete = models.CASCADE)
    user = models.ForeignKey(User, on_delete = models.CASCADE)

    def like(self):
        self.comm_rating += 1
        self.save()


    def dislike(self):
        self.comm_rating -= 1
        self.save()

DraftNews/templates/all_news.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
{% load custom_tags %}
{% load custom_extras %}
{% load i18n %}

{% block title %}
🔥{% trans "All Posts" %}
{% endblock title %}


{% block content %}
   <h1 style="text-align: center;">{% trans "All news and articles" %}</h1>
    <p style="text-align: center;">{% trans "Amount" %}: {{ news|length }}</p>

{% if not is_author %}
<button>
    <a class="nav-link" href="{% url 'account_upgrade' %}">
        <h4><strong>{% trans "Join the authors!" %}</strong></h4>
    </a>
</button>
{% endif %}


   <hr>

{% if news %}


           {% for news in news %}

               <p><strong>{% trans "Title" %}: </strong><a href="{% url 'exactly_news' news.id %}">{{ news.post_title|censor }}</a></p>

               <p><strong>{% trans "Content" %}: </strong>{{ news.post_body|truncatechars:240|censor }}</p>
               <strong>{% trans "Author" %}: </strong>{{ news.author.user }}
               <strong>🕗</strong>{{ news.post_datetime|date:'d M' }}
            <strong>{% trans "Topic" %}</strong>
    {% for cat in news.categories.all %}
                        <a href="{% url 'category_list' cat.id %}">{{ cat.category }}</a>


    {% endfor %}

               <p></p>

{#{% if perms.newsportal.change_post or perms.newsportal.delete_post %}#}
{#                <strong>Действия</strong>#}
{##}
{#{% endif %}#}
 {# А здесь доступ для каждой ссылки теперь будем проверять отдельно #}

                    {% if perms.newsportal.change_post %}
                        {% if news.post_type == "NEWS" %}
                            <button>
                            <a href="{% url 'news_update' pk=news.pk %}">{% trans "Edit" %}</a>
                            </button>
                        {% elif news.post_type == "ARTL" %}
                            <button>
                            <a href="{% url 'artl_update' pk=news.pk %}">{% trans "Edit" %}</a>
                            </button>
                        {% endif %}
                    {% endif %}

                    {% if perms.newsportal.delete_post %}
                    {% if news.post_type == "NEWS" %}
                            <button>
                            <a href="{% url 'news_delete' pk=news.pk %}">{% trans "Delete" %}</a>
                            </button>
                        {% elif news.post_type == "ARTL" %}
                        <button>
                            <a href="{% url 'artl_delete' pk=news.pk %}">{% trans "Delete" %}</a>
                        </button>
                        {% endif %}
                    {% endif %}


<hr /> {#линия отбивки#}
           {% endfor %}

<p style="text-align: center;">
<br> <strong><a href="{% url 'news_search' %}">👀{% trans "Search" %}</a> </strong><br>
   {% else %}
       <h2>{% trans "No posts!" %}</h2>
   {% endif %}
</p>
{# Добавляем пагинацию на страницу #}
   {# Информация о предыдущих страницах #}
<p style="text-align: center;">
{% if page_obj.has_previous %}
    <a href="? url_replace page=1">1</a>
    {% if page_obj.previous_page_number != 1 %}
        ...
        <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
    {% endif %}
{% endif %}

{# Информация о текущей странице #}
{{ page_obj.number }}

{# Информация о следующих страницах #}
{% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}
</p>

{% endblock content %}

DraftNews/templates/category_list.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load custom_tags %}

{% block title %}
{{ category }}
{% endblock title %}


{% block content %}
   <h1 style="text-align: center;">Все посты по теме "{{ category }}"</h1>
    <p style="text-align: center;">Количество постов: {{ category_news_list|length }}</p>

    {% if is_not_subscriber %}
        <p class="text-center"><a href="{% url 'subscribe' category.id%}" class="btn btn-secondary btn-sm"> 👉Подписаться на тему "{{ category }}"</a>  </p>
    {% else %}
       <p class = "text-center"><a href = "{% url 'unsubscribe' category.id %}" class = "btn btn-secondary btn-sm"> 🚫Отписаться от темы "{{ category }}" </a></p>
   {% endif %}

  <hr>

<!--{% if category_news_list %}-->

       {% for news in category_news_list %}

               <p><strong>Название: </strong><a href="{% url 'exactly_news' news.id %}">{{ news.post_title|censor }}</a></p>

               <p><strong>Содержание: </strong>{{ news.post_body|truncatechars:240|censor }}</p>
               <strong>Автор: </strong>{{ news.author.user }}
    <strong>Тема</strong>
    {% for cat in news.categories.all %}
                        <a href="{% url 'category_list' cat.id %}">{{ cat.category }}</a>


    {% endfor %}
<hr />
        {% endfor %}

<p style="text-align: center;">
<br> <strong><a href="{% url 'news_search' %}">👀Поиск</a> </strong><br>
   {% else %}
       <h2>Постов нет!</h2>
   {% endif %}
</p>

{# Добавляем пагинацию на страницу #}
   {# Информация о предыдущих страницах #}
<p style="text-align: center;">
{% if page_obj.has_previous %}
    <a href="? url_replace page=1">1</a>
    {% if page_obj.previous_page_number != 1 %}
        ...
        <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
    {% endif %}
{% endif %}

{# Информация о текущей странице #}
{{ page_obj.number }}

{# Информация о следующих страницах #}
{% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}
</p>


{% endblock content %}

DraftNews/templates/daily_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Новые статьи за последнюю неделю!</h2>
<ul>
    {% for post in posts %}
        <li><a href="{{ link }}{{  post.get_absolute_url }}">{{ post.post_title }}</a> {{post.post_datetime|date:'d M Y'}}</li>
    {% endfor %}
</ul>
</body>
</html>

DraftNews/templates/exactly_news.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

<!-- Название у нас будет Product -->
{% block title %}
📄{{ exactly_news.post_title|censor }}
{% endblock title %}

<!-- В контенте на странице мы выводим сам товар, идентификатор которого был передан в url -->
{% block content %}

               <h1 style="text-align: center;">{{ exactly_news.post_title|censor }}</h1>
    <hr />

               <h6>{{ exactly_news.post_body|censor}}</h6>
    <hr />
<strong>Автор: </strong>{{ exactly_news.author.user }} <strong>
    🕗</strong>{{ exactly_news.post_datetime|date:'d M Y'}} {{ exactly_news.post_datetime|time}}
    <p></p>
<strong>Тема</strong>
    {% for cat in exactly_news.categories.all %}
                        <a href="{% url 'category_list' cat.id %}">{{ cat.category }}</a>


    {% endfor %}
    <p></p>

    {% if perms.newsportal.change_post %}
                        {% if exactly_news.post_type == "NEWS" %}
                            <button>
                            <a href="{% url 'news_update' pk=exactly_news.pk %}">Изменить</a>
                            </button>
                        {% elif exactly_news.post_type == "ARTL" %}
                            <button>
                            <a href="{% url 'artl_update' pk=exactly_news.pk %}">Изменить</a>
                            </button>
                        {% endif %}
                    {% endif %}

                    {% if perms.newsportal.delete_post %}
                    {% if exactly_news.post_type == "NEWS" %}
                            <button>
                            <a href="{% url 'news_delete' pk=exactly_news.pk %}">Удалить</a>
                            </button>
                        {% elif exactly_news.post_type == "ARTL" %}
                        <button>
                            <a href="{% url 'artl_delete' pk=exactly_news.pk %}">Удалить</a>
                        </button>
                        {% endif %}
                    {% endif %}


{% endblock content %}

DraftNews/templates/news_delete.html
{% extends 'flatpages/default.html' %}

{% block title %}
❌Delete?
{% endblock title %}

{% block content %}
<h1 style="text-align: center;">Удаление записи</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p style="text-align: center;">Удаляем запись "{{ object.post_title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

DraftNews/templates/news_edit.html
{% extends 'flatpages/default.html' %}

{% block title %}
✍Edit
{% endblock title %}

{% block content %}



<h1 style="text-align: center;">Редактирование записи</h1>
<hr>

<table style="margin-left: auto; margin-right: auto;">
        <tr>
            <td><form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <table style="margin-left: auto; margin-right: auto;">
            <tr>
                <td>
                    <input type="submit" value="Save" />
                </td>
            </tr>
    </table>
</form>

            </td>
        </tr>
    </table>

{% endblock content %}

DraftNews/templates/news_search.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}
{% load custom_tags %}


{% block title %}
👀Search
{% endblock title %}



{% block content %}

<h1 style="text-align: center;">Поиск</h1>
<hr>

<table style="margin-left: auto; margin-right: auto;">
  <tr>
    <td><form action="" method="get">
       {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}
       <p style="text-align: center;">{{ filterset.form.as_p }}</p>
       {# Добавим кнопку отправки данных формы #}

    <table style="margin-left: auto; margin-right: auto;">
            <tr>
                <td>
                    <input type="submit" value="Найти" />
                </td>
            </tr>
    </table>


        </form>
    </td>
  </tr>
</table>

   <hr>
   {% if news_search %}

           {% for news in news_search %}

               <p><strong>Название: </strong><a href="{% url 'exactly_news' news.id %}">{{ news.post_title|censor }}</a></p>

               <p><strong>Содержание: </strong>{{ news.post_body|truncatechars:240|censor }}</p>
               <strong>Автор: </strong>{{ news.author.user }}
               <strong>Дата: </strong>{{ news.post_datetime|date:'d M' }}
            <strong>Тема</strong>
    {% for cat in news.categories.all %}
                        <a href="{% url 'category_list' cat.id %}">{{ cat.category }}</a>


    {% endfor %}
               <p></p>
<hr /> {#линия отбивки#}
           {% endfor %}

       </table>
   {% else %}
       <h2>Постов нет!</h2>
   {% endif %}
</p>
{# Добавляем пагинацию на страницу #}
   {# Информация о предыдущих страницах #}

<p style="text-align: center;">
{% if page_obj.has_previous %}
    <a href="? url_replace page=1">1</a>
    {% if page_obj.previous_page_number != 1 %}
        ...
        <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
    {% endif %}
{% endif %}

{# Информация о текущей странице #}
{{ page_obj.number }}

{# Информация о следующих страницах #}
{% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}
</p>

{% endblock content %}

DraftNews/templates/post_created_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Здравствуй! Новая <a href="{{ link }}">статья</a> в твоём любимом разделе</h2>
<p>{{ text }}</p>
</body>
</html>

DraftNews/templates/subscribe.html
{% extends 'flatpages/default.html' %}

{% block title %}
🔔Subscribe
{% endblock title %}

{% block content %}

<h1 class="text-center">{{ message }} </h1>

{% endblock content%}

DraftNews/templates/subscriptions.html
{% extends 'flatpages/default.html' %}

{% block title %}
Subscriptions
{% endblock title %}

{% block content %}
    {% for new in news  %}
        <p>
            {{ new.post_type }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="post_type" value="{{ post_type.id }}" />

                {% if news.user_subscribed %}
                    <button disabled>Подписаться</button>
                    <button name="action" value="unsubscribe">Отписаться</button>
                {% else %}
                    <button name="action" value="subscribe">Подписаться</button>
                    <button disabled>Отписаться</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}

DraftNews/templates/unsubscribe.html
{% extends 'flatpages/default.html' %}

{% block title %}
🚫Unsubscribe
{% endblock title %}

{% block content %}
<h1 class="text-center">{{ message }} </h1>
{% endblock content%}